language: php

sudo: true

php:
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - MODULAR_VERSION=dev-master LARAVEL_VERSION=5.0.* LARAVEL_FOLDER=laravel5.0
    - MODULAR_VERSION=dev-master LARAVEL_VERSION=5.1.* LARAVEL_FOLDER=laravel5.1
    - MODULAR_VERSION=dev-master LARAVEL_VERSION=5.2.* LARAVEL_FOLDER=laravel5.2
    - MODULAR_VERSION=dev-master LARAVEL_VERSION=dev-develop LARAVEL_FOLDER=laravel5.3
    - MODULAR_VERSION=dev-develop LARAVEL_VERSION=5.0.* LARAVEL_FOLDER=laravel5.0
    - MODULAR_VERSION=dev-develop LARAVEL_VERSION=5.1.* LARAVEL_FOLDER=laravel5.1
    - MODULAR_VERSION=dev-develop LARAVEL_VERSION=5.2.* LARAVEL_FOLDER=laravel5.2
    - MODULAR_VERSION=dev-develop LARAVEL_VERSION=dev-develop LARAVEL_FOLDER=laravel5.3

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - ${LARAVEL_FOLDER}/vendor

install:
  - export PACKAGE_PROVIDER="LaraLibs\\\\Modular\\\\ModularServiceProvider::class"
  - export PACKAGE_NAME=laralibs/modular
  - curl -s https://raw.githubusercontent.com/laravel-libraries/modular/master/build.sh | bash

script:
  - cd ${LARAVEL_FOLDER}
  - composer require ${PACKAGE_NAME}:${MODULAR_VERSION}
  - composer update
  #- cat config/app.php
  #- ls vendor/laralibs/modular
  - sudo php artisan cache:clear
  - sudo php artisan config:clear
  - sudo vendor/bin/phpunit -c vendor/${PACKAGE_NAME}/phpunit.xml
  #- ls modules/ -R

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
