language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - GIT_BRANCH=dev-master
    - GIT_BRANCH=dev-develop

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel/vendor

install:
  - export PACKAGE_PROVIDER="LaraLibs\\\\Modular\\\\ModularServiceProvider::class"
  - export PACKAGE_NAME=laralibs/modular
  - curl -s https://raw.githubusercontent.com/laravel-libraries/modular/master/build.sh | bash

script:
  - cd laravel
  - composer require ${PACKAGE_NAME}:${GIT_VERSION}
  - composer update
  #- cat config/app.php
  #- ls vendor/laralibs/modular
  - sudo php artisan cache:clear
  - sudo php artisan config:clear
  - sudo vendor/bin/phpunit -c vendor/${PACKAGE_NAME}/phpunit.xml
  #- ls modules/ -R

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
