language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

install:
  - export PACKAGE_PROVIDER="
    LaraLibs\\\\Modular\\\\ModularServiceProvider::class"
  - export PACKAGE_NAME=laralibs/modular
  - curl -s https://raw.githubusercontent.com/laravel-libraries/modular/master/build.sh | bash

script:
  - cd laravel
  - composer update
  - php artisan cache:clear
  - php artisan config:clear
  - phpunit -c vendor/$PACKAGE_NAME/phpunit.xml

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
