language: php

sudo: true

php:
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - LARAVEL_FOLDER=laravel50    LARAVEL_VERSION=5.0.*
    - LARAVEL_FOLDER=laravel51    LARAVEL_VERSION=5.1.*
    - LARAVEL_FOLDER=laravel52    LARAVEL_VERSION=5.2.*
    - LARAVEL_FOLDER=laravel53    LARAVEL_VERSION=dev-develop

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - ${LARAVEL_FOLDER}

before_cache:
  - rm ${LARAVEL_FOLDER}/storage/framework/compiled.php
  - rm ${LARAVEL_FOLDER}/vendor/compiled.php
  - rm -rf ${LARAVEL_FOLDER}/modules
  - rm -rf ${LARAVEL_FOLDER}/resources/views/vendor/modular

install:
  - export PACKAGE_NAME=laralibs/modular
  - export PACKAGE_PROVIDER="LaraLibs\\\\Modular\\\\ModularServiceProvider::class"
  - curl -s https://raw.githubusercontent.com/laravel-libraries/modular/${TRAVIS_BRANCH}/build.sh | bash

script:
  - curl -s https://raw.githubusercontent.com/laravel-libraries/modular/${TRAVIS_BRANCH}/script.sh | bash

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
